name: 'learn-ansible'

x-ubuntu: &ubuntu
  build:
    context: docker/ubuntu
  volumes:
    - ./ssh:/ssh
  environment:
    SSH_USERNAME: 'vagrant'
    SSH_PASSWORD: 'vagrant'
  hostname: ubuntu
  networks:
    - net

services:
  control:
    build:
      context: docker/control
    volumes:
      - ./ansible:/ansible
      - ./ssh:/ssh
    working_dir: /ansible
    hostname: control
    networks:
      - net

  ubuntu-1:
    <<: *ubuntu
    hostname: ubuntu-1

  ubuntu-2:
    <<: *ubuntu
    hostname: ubuntu-2

  ubuntu-3:
    <<: *ubuntu
    hostname: ubuntu-3

networks:
  net:
    driver: bridge
